name: Continuous Integration

on: ['pull_request']

jobs:
  webservice:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: xdebug

      - name: Validate composer.json and composer.lock
        working-directory: webservice
        run: composer validate --no-check-publish --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: webservice/vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Dependencies
        working-directory: webservice
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

      #- name: Lint Twig Templates
      #  working-directory: webservice
      #  TODO check which folder was changed
      #  run: composer run lint:twig

      - name: Check Code Style (PHP)
        run: |
          IFS='
          '
          CHANGED_FILES=$(git diff --name-only --relative --diff-filter=ACMRTUXB "${{ github.event_name == 'push' && github.event.pull_request.base.sha || github.event.before }}..${{ github.sha }} -- webservice")
          if ! echo "${CHANGED_FILES}" | grep -qE "^(\\.php-cs-fixer(\\.dist)?\\.php|composer\\.lock)$"; then EXTRA_ARGS=$(printf -- '--path-mode=intersection\n--\n%s' "${CHANGED_FILES}"); else EXTRA_ARGS=''; fi
          cd webservice
          vendor/bin/php-cs-fixer check --config.php-cs-fixer.dist.php -v --stop-on-violation --using-cache=no ${EXTRA_ARGS}

      - name: Tests
        working-directory: webservice
        run: ./vendor/bin/pest